# **** CONF's COLETA ****

# DIAS DE VENCIMENTO APÓS A COLETA 
VENCIMENTO_SANGUE = 35


# **** CONF's DOADORES ****
# REQUISITOS
IDADE_MINIMA = 16
IDADE_MAXIMA = 60
PESO_MINIMO = 50

# MÁXIMO DE DOAÇOES POR ANO 
TOTAL_DOACAO_ANO_HOMEM = 4
TOTAL_DOACAO_ANO_MULHER = 3

# NUMERO DE DIAS DESDE A ULTIMA DOAÇÃO
INTERVALO_DOACAO_HOMEM = 60
INTERVALO_DOACAO_MULHER = 90



# **** CONF's COLETA ****

# TOTAL DA COLETA EM mL (420ml e 470ml de sangue, além de 25ml a 30ml P/ EXAMES)
QTDE_MININA_COLETA = 420
QTDE_MAXIMA_COLETA = 520

# Quantidade em ml de uma unidade(1 bolsa de sangue)
UNIDADE_ml = 450 