# Generated by Django 5.0.3 on 2024-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
