# Generated by Django 5.0.3 on 2024-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0002_alter_doador_cep_alter_doador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
