# Generated by Django 5.0.3 on 2024-04-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0003_alter_doador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cep',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='doador',
            name='complemento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.IntegerField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='ultima_doacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
