# Generated by Django 5.0.3 on 2024-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0005_alter_doador_cep_alter_doador_cpf_alter_doador_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='fator_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doador',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=100, null=True),
        ),
    ]
