# Generated by Django 5.0.3 on 2024-04-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0006_doador_fator_rh_doador_tipo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='fator_rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True),
        ),
    ]
