# Generated by Django 5.0.3 on 2024-04-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0007_alter_doador_fator_rh_alter_doador_tipo_sanguineo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='peso_aproximado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
