# Generated by Django 5.0.3 on 2024-04-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0008_doador_peso_aproximado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='peso_aproximado',
            field=models.PositiveIntegerField(),
        ),
    ]
