# Generated by Django 5.0.3 on 2024-04-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0009_alter_doador_peso_aproximado'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='genero',
            field=models.CharField(choices=[('HOMEM CISGÊNERO', 'HOMEM CISGÊNERO'), ('MULHER CISGÊNERO', 'MULHER CISGÊNERO'), ('HOMEM TRANSGÊNERO', 'HOMEM TRANSGÊNERO'), ('MULHER TRANSGÊNERO', 'MULHER TRANSGÊNERO'), ('NÃO-BINÁRIO', 'NÃO-BINÁRIO'), ('AGÊNERO', 'AGÊNERO')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doador',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
