# Generated by Django 5.0.3 on 2024-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0011_alter_doador_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='genero',
            field=models.CharField(blank=True, choices=[('Homem cisgênero', 'Homem Cisgênero'), ('Mulher cisgênero', 'MULHER cisgênero'), ('HOMEM transgênero', 'HOMEM transgênero'), ('Mulher transgênero', 'Mulher transgênero'), ('Não-binário', 'Não-binário'), ('Agênero', 'Agênero')], max_length=20, null=True),
        ),
    ]
