# Generated by Django 5.0.3 on 2024-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0012_alter_doador_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.BigIntegerField(unique=True),
        ),
    ]
