# Generated by Django 5.0.3 on 2024-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0016_alter_doador_latitude_alter_doador_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
