# Generated by Django 5.0.3 on 2024-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0017_alter_doador_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='obs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
