# Generated by Django 5.0.3 on 2024-04-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0018_doador_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='peso_aproximado',
            field=models.FloatField(),
        ),
    ]
