# Generated by Django 5.0.3 on 2024-04-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0005_alter_hemocentro_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hemocentro',
            name='created_at',
        ),
    ]
