# Generated by Django 5.0.3 on 2024-04-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0009_alter_hemocentro_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocentro',
            name='complemento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
