# Generated by Django 5.0.3 on 2024-04-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0011_alter_hemocentro_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocentro',
            name='estoque_atual',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hemocentro',
            name='estoque_ideal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
