# Generated by Django 5.0.3 on 2024-04-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0012_hemocentro_estoque_atual_hemocentro_estoque_ideal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocentro',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hemocentro',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
