# Generated by Django 5.0.3 on 2024-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0013_hemocentro_latitude_hemocentro_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocentro',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
