# Generated by Django 5.0.3 on 2024-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0014_hemocentro_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocentro',
            name='obs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
