# Generated by Django 5.0.3 on 2024-04-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0015_hemocentro_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemocentro',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
