# Generated by Django 5.0.3 on 2024-04-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0016_alter_hemocentro_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemocentro',
            name='sigla',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
