# Generated by Django 5.0.3 on 2024-04-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, choices=[('coleta', 'Coleta'), ('movimentacao', 'Movimentação')], max_length=20, null=True)),
                ('cpf', models.BigIntegerField()),
                ('hemocentro', models.IntegerField()),
                ('quantidade', models.FloatField()),
                ('data_hora', models.DateTimeField()),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=20, null=True)),
                ('fator_rh', models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('realocado', 'Indisponível/Realocado'), ('vencido', 'Indiponível/Vencido')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
