# Generated by Django 5.0.3 on 2024-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0002_alter_coleta_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('recebido', 'Disponível/Recebido'), ('enviado', 'Indisponível/Enviado'), ('vencido', 'Indiponível/Vencido')], max_length=20),
        ),
    ]
