# Generated by Django 5.0.3 on 2024-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0004_coleta_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='destino',
            field=models.CharField(blank=True, null=True, max_length=100),
            preserve_default=False,
        ),
    ]
