# Generated by Django 5.0.3 on 2024-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0006_alter_coleta_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='unidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
