# Generated by Django 5.0.3 on 2024-04-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0008_alter_coleta_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='origem',
            field=models.CharField(blank=True, null=True, max_length=100),
        ),
    ]
