# Generated by Django 5.0.3 on 2024-04-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditlogLogentry',
            new_name='auditlog_logentry',
        ),
    ]
