# Generated by Django 5.0.3 on 2024-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_auditloglogentry_auditlog_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogLogentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('object_repr', models.TextField()),
                ('action', models.SmallIntegerField()),
                ('changes', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('serialized_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditlog_logentry',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='auditlog_logentry',
        ),
    ]
